# Price tracking settings
find_prices: True # True: Use price tracking feature
price_tracking_array:
  start: 1
  stop: 10
  step: 0.05
price_hubs: all
#["austin", "pasadena"] # "all"
price_demand: 1.0E-5

# Carbon settings, should maybe be a csv file
carbon_price_dollars_per_ton: 0
carbon_capture_credit_dollars_per_ton: 50
baseSMR_CO2_per_H2_tons: 9 # the co2 mass per h2 mass that defines 0 CHECs.

# Subsidy settings, should maybe be a csv file
subsidy_dollar_billion: 0
subsidy_cost_share_fraction: 0.9

# Investment settings, should maybe be a csv file
investment_interest: 0.06
investment_period: 20
time_slices: 365

# percent of capital used to estimate fixed costs
fixedcost_percent: 0.02

# Solver settings
solver_settings:
  solver: "gurobi"
  solver_debug: False
  mipgap: 1.0E-2

# other options
fractional_chec: True # True - CHECs are assigned based on carbon free hydrogen, False - CHECs are given for all production if producer has any form of carbon reduction

# optional options
hubs_dir: c:\\users\\ursuline\\research\\version3\\scenarios\\base\\inputs\\data # otherwise, uses what is specified in data/data_mapping.yml
